# Render example:
# > go get github.com/noqcks/gucci@1.5.0
# openshift:
# > ~/go/bin/gucci -s "RUNTIME_ENDPOINT=unix:///run/crio/crio.sock" \
#                  -s "MTU=9000" \
#                  -s "MTU_CHECK_OFFSET=100" \
#                  -s "POD_NETWORK=10.128.0.0/14" \
#                  -s "CNO_CONFIG_PATH=/etc/cno-config" \
#                  -s "NODENAME=worker-a" \
#                  dist/templates/cno-mtu-setter-pod.yaml.tpl
# kind:
# > ~/go/bin/gucci -s "RUNTIME_ENDPOINT=unix:///run/containerd/containerd.sock" \
#                  -s "MTU=9000" \
#                  -s "MTU_CHECK_OFFSET=100" \
#                  -s "POD_NETWORK=10.244.1.0/16" \
#                  -s "NODENAME=ovn-worker-2" \
#                  dist/templates/cno-mtu-setter-pod.yaml.tpl
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: cno-pod-mtu-setter
  name: cno-pod-mtu-setter
  namespace: openshift-network-operator
spec:
  hostNetwork: true
  initContainers:
  - name: cno-pod-mtu-check
    image: quay.io/jcaamano/cno-pod-mtu-setter
    args:
    - --runtime-endpoint
    - $(RUNTIME_ENDPOINT)
    - --pod-network
    - $(POD_NETWORK)
    - --mtu
    - $(MTU)
    - --mtu-check-offset
    - $(MTU_CHECK_OFFSET)
    - --dry-run
    - true
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
    env:
    - name: RUNTIME_ENDPOINT
      value: unix:///run/crio/crio.sock
    - name: POD_NETWORK
      value: 10.128.0.0/14
    - name: MTU
      value: "9000"
    - name: MTU_CHECK_OFFSET
      value: "100"
    volumeMounts:
    - name: runtime-endpoint
      mountPath: unix:///run/crio/crio.sock
    - name: netns
      mountPath: /var/run/netns
  containers:
  - name: cno-pod-mtu-set
    image: quay.io/jcaamano/cno-pod-mtu-setter
    args:
    - --runtime-endpoint
    - $(RUNTIME_ENDPOINT)
    - --pod-network
    - $(POD_NETWORK)
    - --mtu
    - $(MTU)
    - --mtu-check-offset
    - $(MTU_CHECK_OFFSET)
    - --cno-config-path
    - $(CNO_CONFIG_PATH)
    - --cno-config-ready-path
    - /tmp/ready
    securityContext:
      capabilities:
        add: ["NET_ADMIN", "SYS_ADMIN"]
    env:
    - name: RUNTIME_ENDPOINT
      value: unix:///run/crio/crio.sock
    - name: POD_NETWORK
      value: 10.128.0.0/14
    - name: MTU
      value: "9000"
    - name: MTU_CHECK_OFFSET
      value: "100"
    - name: CNO_CONFIG_PATH
      value: /run/cno-pod-mtu-setter//etc/cno-config
    volumeMounts:
    - name: runtime-endpoint
      mountPath: unix:///run/crio/crio.sock
    - name: netns
      mountPath: /var/run/netns
    - name: config-volume
      mountPath: /run/cno-pod-mtu-setter//etc
    readinessProbe:
      exec:
        command:
          - cat
          - /tmp/ready
      periodSeconds: 1
      failureThreshold: 1
  volumes:
  - name: runtime-endpoint
    hostPath:
      path: unix:///run/crio/crio.sock
  - name: netns
    hostPath:
      path: /var/run/netns
  - name: config-volume
    configMap:
      name: applied-cluster
      items:
      - key: applied
        path: cno-config
  restartPolicy: Never
  nodeName: worker-a
  